#!/usr/bin/env bash
# ════════════════════════════════════════════════════════════
# build_with_redpanda.sh — Build & launch SkillScale (Redpanda)
#
# This script mirrors build.sh structure but for the Kafka/Redpanda stack.
# It dynamically generates docker-compose-redpanda.yml based on available skills.
#
# Usage:
#   bash build_with_redpanda.sh              # full clean + build + launch
#   bash build_with_redpanda.sh --no-clean   # build + launch (skip cleaning)
#   bash build_with_redpanda.sh --build-only # build images only
#   bash build_with_redpanda.sh --down       # stop all containers
# ════════════════════════════════════════════════════════════
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

# ── Colors ──
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'

log()  { echo -e "${GREEN}[build-rp]${NC} $*"; }
warn() { echo -e "${YELLOW}[build-rp]${NC} $*"; }
err()  { echo -e "${RED}[build-rp]${NC} $*" >&2; }
step() { echo -e "\n${CYAN}${BOLD}══ $* ══${NC}"; }

# ── Parse flags ──
NO_CLEAN=false
BUILD_ONLY=false
DOWN_ONLY=false

for arg in "$@"; do
    case "$arg" in
        --no-clean)   NO_CLEAN=true ;;
        --build-only) BUILD_ONLY=true ;;
        --down)       DOWN_ONLY=true ;;
        --help|-h)
            echo "Usage: bash build_with_redpanda.sh [OPTIONS]"
            echo "  --no-clean    Skip cleaning compiled artifacts"
            echo "  --build-only  Build images only, don't launch"
            echo "  --down        Stop all containers and exit"
            echo "  -h, --help    Show this help"
            exit 0
            ;;
        *) err "Unknown option: $arg"; exit 1 ;;
    esac
done

# ── Handle --down ──
if $DOWN_ONLY; then
    step "Stopping all Redpanda Stack containers"
    docker compose -f docker-compose-redpanda.yml down 2>/dev/null || true
    log "All containers stopped."
    exit 0
fi

# ════════════════════════════════════════════════════════════
# 1. Load .env
# ════════════════════════════════════════════════════════════
step "Loading configuration from .env"

if [[ ! -f .env ]]; then
    err ".env file not found! Create one from .env.example or configure manually."
    exit 1
fi

set -a
source .env
set +a

# Validate required keys
REQUIRED_VARS=(OPENAI_API_KEY OPENAI_API_BASE OPENAI_MODEL SKILLSCALE_TIMEOUT PUBLISH_TIMEOUT LLM_PROVIDER)
for var in "${REQUIRED_VARS[@]}"; do
    if [[ -z "${!var:-}" ]]; then
        err "Required variable $var is not set in .env"
        exit 1
    fi
done

log "Configuration loaded. Provider: ${LLM_PROVIDER}"

# ════════════════════════════════════════════════════════════
# 2. Clean compiled artifacts
# ════════════════════════════════════════════════════════════
if ! $NO_CLEAN; then
    step "Cleaning artifacts (Python)"
    find . -type d -name "__pycache__" -not -path "./.venv/*" -exec rm -rf {} + 2>/dev/null || true
    find . -type f -name "*.pyc" -not -path "./.venv/*" -delete 2>/dev/null || true
    rm -rf skillscale.egg-info/ 2>/dev/null || true
    log "Clean complete."
else
    log "Skipping clean (--no-clean)."
fi

# ════════════════════════════════════════════════════════════
# 2.5 Build C++ Skill Server (Local)
# ════════════════════════════════════════════════════════════
step "Building Local C++ Skill Server..."

if ! command -v cmake &> /dev/null; then
    err "cmake could not be found. Please install cmake."
    exit 1
fi

# Build directory for skill-server
mkdir -p build/skill-server
pushd build/skill-server > /dev/null

log "Configuring CMake (skill-server)..."
cmake ../../skill-server -DCMAKE_BUILD_TYPE=Release

log "Compiling..."
# macOS: sysctl -n hw.ncpu; Linux: nproc
CORES=$(sysctl -n hw.ncpu 2>/dev/null || nproc 2>/dev/null || echo 2)
make -j"$CORES"

popd > /dev/null
log "C++ Build Complete (skill-server)."

# ════════════════════════════════════════════════════════════
# 3. Generate docker-compose-redpanda.yml
# ════════════════════════════════════════════════════════════
# step "Scanning skills/ and generating docker-compose-redpanda.yml"

# With C++ build, we only need the REDPANDA service. 
# The SKILL SERVERS run as C++ binaries locally.
# The AGENT and GATEWAY run as Python processes locally.
# So the docker-compose needed is just: Redpanda.

log "Generating simple docker-compose-redpanda.yml (Broker Only)"

COMPOSE_FILE="docker-compose-redpanda.yml"

# Base Compose content (Redpanda + Console)
cat > "$COMPOSE_FILE" <<'HEADER'
# SkillScale — Redpanda (Kafka) Deployment
# Generated by build_with_redpanda.sh — DO NOT EDIT MANUALLY
#
services:
  # ── Redpanda Broker ──
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v23.3.6
    command:
      - redpanda
      - start
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --overprovisioned
      - --node-id 0
      - --check=false
      - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:19092
      - --advertise-kafka-addr PLAINTEXT://redpanda:29092,OUTSIDE://localhost:19092
      - --pandaproxy-addr 0.0.0.0:8082
      - --advertise-pandaproxy-addr localhost:8082
    ports:
      - "8081:8081"
      - "8082:8082"
      - "19092:19092"
      - "9092:9092"
      - "9644:9644"
    volumes:
      - redpanda-data:/var/lib/redpanda/data
    healthcheck:
      test: ["CMD-SHELL", "rpk cluster health | grep -q 'Healthy:.*true'"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ── Redpanda Console (Web UI) ──
  console:
    image: docker.redpanda.com/redpandadata/console:v2.4.3
    entrypoint: /bin/sh
    command: -c "echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yaml && /app/console"
    environment:
      CONFIG_FILEPATH: /tmp/config.yaml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda:29092"]
          schemaRegistry:
            enabled: false
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://redpanda:9644"]
    ports:
      - "8080:8080"
    depends_on:
      - redpanda

volumes:
  redpanda-data:

HEADER
log "Generated docker-compose-redpanda.yml."

# ════════════════════════════════════════════════════════════
# 4. Build Containers

# ════════════════════════════════════════════════════════════
step "Building Docker images"

docker compose -f "$COMPOSE_FILE" build

if $BUILD_ONLY; then
    log "Build only complete."
    exit 0
fi

# ════════════════════════════════════════════════════════════
# 5. Launch Stack
# ════════════════════════════════════════════════════════════
step "Launching Redpanda Stack"
docker compose -f "$COMPOSE_FILE" up -d redpanda console

log "Waiting for Redpanda Broker to stabilize..."
sleep 5

docker compose -f "$COMPOSE_FILE" up -d

log "Redpanda Stack Running!"
exit 0
