import asyncio
import json
import logging
import uuid
from typing import Any, Dict, Optional

# import MCP (Model Context Protocol) SDKs (e.g. mcp, fastmcp)
try:
    from mcp.server.fastmcp import FastMCP
except ImportError:
    FastMCP = None

from fastapi import FastAPI, Request
import uvicorn

from datetime import datetime
from pydantic import ValidationError

from a2a_protocol.pydantic_v2 import (
    SendTaskRequest,
    SendTaskResponse,
    Task,
    TaskStatus,
    TaskState,
    Message,
    Role,
    Part,
    TextPart
)

from skillscale.client import SkillScaleClient, ClientConfig

log = logging.getLogger("skillscale.gateway")

class TransparentGateway:
    """
    Transparent Gateway replacing ZeroMQ bus for external clients via Model Context Protocol (MCP)
    and Google Agent-to-Agent (A2A). Internally, it translates these protocols into standard
    ZeroMQ pub/sub messages to leverage the existing high-performance bus.
    """

    def __init__(self, config: Optional[ClientConfig] = None):
        self.config = config or ClientConfig.from_env()
        self.zmq_client = SkillScaleClient(self.config)
        self.mcp = FastMCP("SkillScaleMCPGateway") if FastMCP else None
        
        self.setup_mcp_tools()
        self.setup_a2a_routes()

    async def start(self):
        """Starts the gateway services."""
        await self.zmq_client.connect()
        log.info("ZMQ transparent layer connected.")
        
        # Start protocol servers asynchronously
        tasks = []
        if self.mcp:
            tasks.append(asyncio.create_task(self._start_mcp_server()))
        tasks.append(asyncio.create_task(self._start_a2a_server()))
        
        await asyncio.gather(*tasks)

    # =========================================================================
    # MCP Protocol Bridge
    # =========================================================================
    def setup_mcp_tools(self):
        """Register MCP tools that dynamically route to ZMQ topics/skills."""
        if not self.mcp:
            log.warning("FastMCP not installed, skipping MCP setup.")
            return

        @self.mcp.tool()
        async def invoke_skill(category: str, skill_name: str, payload: Dict[str, Any]) -> str:
            """
            Expose internal ZMQ skills to MCP clients.
            This routes an MCP tool call transparently over ZMQ to the corresponding Skill Server.
            """
            topic = f"TOPIC_{category.upper().replace('-', '_')}"
            
            # Pack MCP payload AND CONTEXT into SkillScale format
            # In a real scenario, context (like user ID, session history) would be extracted from the MCP request
            zmq_payload = {
                "skill": skill_name,
                "data": payload,
                "context": {
                    "session_id": "mcp_session_xxx",  # Placeholder for real MCP trace/session
                    "shared_memory": {},              # Any A2A or MCP shared state
                    "protocol": "mcp/1.0"
                },
                "metadata": {"source": "mcp-gateway"}
            }
            
            log.info(f"[MCP] Routing tool '{skill_name}' to ZMQ '{topic}' with context.")
            
            # Send through the transparent ZMQ bus. SkillScale invoke expects a JSON string intent.
            reply = await self.zmq_client.invoke(topic, json.dumps(zmq_payload), timeout=60.0)
            return json.dumps(reply)

        @self.mcp.resource("skillscale://context/{session_id}")
        async def get_shared_context(session_id: str) -> str:
            """
            Expose internal ZeroMQ shared state/context as an MCP Resource.
            This allows MCP clients (like Claude Desktop) to read the context 
            generated by other Agents on the ZeroMQ bus.
            """
            log.info(f"[MCP] Client requested shared context for session {session_id}")
            # Ask the ZMQ bus for the latest state of this session
            zmq_payload = {"action": "get_state", "session_id": session_id}
            reply = await self.zmq_client.invoke("TOPIC_CONTEXT_SYNC", json.dumps(zmq_payload), timeout=5.0)
            return json.dumps(reply)

    async def _start_mcp_server(self):
        """Run the MCP server (Stdio or SSE)."""
        log.info("Starting MCP Server bridge...")
        # Start Stdio server for MCP clients
        if self.mcp:
            await self.mcp.run_stdio_async()

    # =========================================================================
    # Google Agent-to-Agent (A2A) Bridge
    # =========================================================================
    def setup_a2a_routes(self):
        """Setup routes for Google Agent-to-Agent (A2A) specifications."""
        self.a2a_app = FastAPI(title="SkillScale A2A Bridge")

        @self.a2a_app.post("/v1/agents/{agent_id}/converse")
        async def a2a_converse(agent_id: str, request: Request):
            payload = await request.json()
            
            try:
                # Parse using official A2A SDK
                a2a_req = SendTaskRequest.model_validate(payload)
            except ValidationError as e:
                return {"jsonrpc": "2.0", "error": {"code": -32602, "message": f"Invalid params: {e}"}, "id": payload.get("id")}
            
            log.info(f"[A2A] Received converse request for target agent (skill) '{agent_id}'")
            
            # Transparent middleware should be completely agnostic.
            # Extract the raw intent from A2A message parts generically.
            extracted_text = ""
            for part in a2a_req.params.message.parts:
                if isinstance(part.root, TextPart):
                    extracted_text += part.root.text + "\n"
                    
            # Extract target topic from A2A metadata (standard mechanism for routing hints)
            target_topic = "TOPIC_DEFAULT"
            if a2a_req.params.metadata and "topic" in a2a_req.params.metadata:
                target_topic = a2a_req.params.metadata["topic"]
            
            # Map Google A2A protocol structure back into our ZeroMQ bus intent model
            zmq_payload = {
                "skill": agent_id,
                "data": {"input": extracted_text.strip()},
                "context": {
                    "session_id": a2a_req.params.sessionId or "default_session",
                    "sender": a2a_req.params.id,
                    "protocol": "a2a/1.0"
                },
                "metadata": {"source": "google-a2a-gateway", "a2a_request_id": str(a2a_req.id)}
            }
            
            # Send to ZMQ
            reply = await self.zmq_client.invoke(target_topic, json.dumps(zmq_payload), timeout=120.0)
            
            # Pack ZMQ reply back into Google A2A expected SendTaskResponse protocol structure
            a2a_resp = SendTaskResponse(
                jsonrpc="2.0",
                id=a2a_req.id,
                result=Task(
                    id=a2a_req.params.id,
                    sessionId=a2a_req.params.sessionId,
                    status=TaskStatus(
                        state=TaskState.completed,
                        timestamp=datetime.utcnow()
                    ),
                    history=[
                        Message(
                            role=Role.agent,
                            parts=[Part(root=TextPart(type="text", text=str(reply)))]
                        )
                    ]
                )
            )
            
            return a2a_resp.model_dump(exclude_none=True)

    async def _start_a2a_server(self):
        """Mock A2A server running on a specific port."""
        log.info("Starting Google A2A Server bridge on port 8081...")
        config = uvicorn.Config(self.a2a_app, host="127.0.0.1", port=8081, log_level="error")
        server = uvicorn.Server(config)
        await server.serve()

    async def stop(self):
        await self.zmq_client.close()

if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    gateway = TransparentGateway()
    asyncio.run(gateway.start())
